--- #YAML:1.0
name:               Tail-Stat
version:            0.01
abstract:           Real-time log statistics server
author:
    - Oleg A. Mamontov <oleg@mamontov.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DateTime:            0
    JSON::XS:            0
    Log::Dispatch:       2.26
    Pid::File::Flock:    0
    POE:                 0
    Sys::Syslog:         0.16
    Test::More:          0
    Tie::Hash::Indexed:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
