---
abstract: 'Real-time log statistics server'
author:
  - 'Oleg A. Mamontov, C<< <oleg@mamontov.net> >>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
  Test::TCP: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tail-Stat
no_index:
  directory:
    - inc
    - t
requires:
  DateTime: 0
  JSON::XS: 0
  Log::Dispatch: 2.26
  POE: 0
  Pid::File::Flock: 0
  Sys::Syslog: 0.16
  Tie::Hash::Indexed: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.20
